### ISSUE TITLE
CIL_FRAMEWORK_TESTS_1 are failing with libcilacc.so

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#389]
All +cil jobs are failing in https://github.com/SyneRBI/SIRF-SuperBuild/pull/387. 
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/builds/682882279 see eg.
https://api.travis-ci.org/v3/job/682882281/log.txt
```
5/8 Test #5: CIL_FRAMEWORK_TESTS_1 ............***Failed    0.24 sec
EE
======================================================================
ERROR: test_DataContainer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_DataContainer
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/SyneRBI/SIRF-SuperBuild/sources/CCPi-Framework/Wrappers/Python/test/test_DataContainer.py", line 23, in <module>
    from ccpi.framework import DataContainer
  File "/home/travis/build/SyneRBI/SIRF-SuperBuild/INSTALL/python/ccpi/framework/__init__.py", line 28, in <module>
    from .framework import DataContainer
  File "/home/travis/build/SyneRBI/SIRF-SuperBuild/INSTALL/python/ccpi/framework/framework.py", line 47, in <module>
    cilacc = ctypes.cdll.LoadLibrary(dll)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcilacc.so: cannot open shared object file: No such file or directory
```
Most likely we're still using CIL `master`  tag.

@paskino can this be sorted out at high priority please?

**Comment by KrisThielemans** [comment]
no longer using `master`
https://github.com/SyneRBI/SIRF-SuperBuild/blob/dfd7e9795fe94457e86498a5fe7f9bb0f30c6d33/version_config.cmake#L157-L165
so I don't know what's happening

**Comment by KrisThielemans** [comment]
@paskino, @epapoutsellis can you have a look at this please? It kills both CIL and CIL_LITE tests (1 and 3). here's another job https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/683356036

**Comment by KrisThielemans** [comment]
This one was 4 days old and worked fine. https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/builds/681959947. We didn't change anything in the mean time.

**Comment by paskino** [comment]
I suppose we need to upgrade the CIL version tag to 20.04.
I need to fix something in the regularisation toolkit and will make a PR.
