### ISSUE TITLE
Docker on mac: permission error with user and group

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#609]
The [error](https://hackmd.io/kZx9QmOSRUWQEUtGprZujw#Q-Docker-my-docker-instance-fails-to-start-on-a-Mac) came out during the training. An initial fix with #607 has been merged in but the error persists.

```
Creating sirfuser:503:20
addgroup: The GID `20' is already in use.
Adding user `sirfuser' to group `users' ...
Adding user sirfuser to group users
Done.
Updating file ownership for /home/sirfuser
chown: invalid group: ‘sirfuser:sirfuser’
Switching to sirfuser and executing /usr/local/bin/service.sh
ccache: error: /home/sirfuser/.ccache/ccache.conf: No such file or directory
.bashrc: line 12: /home/sirfuser/.git-prompt.sh: Permission denied
.bashrc: line 14: /home/sirfuser/.git-prompt.sh: No such file or directory
/opt/SIRF-SuperBuild ~
start gadgetron
make sure the SIRF-Exercises and CIL-Demos are in the expected location (/devel in the container)
/usr/local/bin/service.sh: line 37: /home/sirfuser/gadgetron.log: Permission denied
start jupyter
Writing default config to: /home/sirfuser/.jupyter/jupyter_notebook_config.py
Traceback (most recent call last):
  File "/opt/pyvenv/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/opt/pyvenv/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/pyvenv/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/opt/pyvenv/lib/python3.8/site-packages/notebook/notebookapp.py", line 2282, in start
    super().start()
  File "/opt/pyvenv/lib/python3.8/site-packages/jupyter_core/application.py", line 247, in start
    self.write_default_config()
  File "/opt/pyvenv/lib/python3.8/site-packages/jupyter_core/application.py", line 139, in write_default_config
    ensure_dir_exists(os.path.abspath(os.path.dirname(config_file)), 0o700)
  File "/opt/pyvenv/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/pyvenv/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/sirfuser/.jupyter'
/usr/local/bin/service.sh: line 55: /home/sirfuser/.jupyter/jupyter_notebook_config.py: No such file or directory
```

I'm wondering if we shouldn't just use the group id and user id as numbers rather than names.

**Comment by KrisThielemans** [comment]
yeah. offending line is
https://github.com/SyneRBI/SIRF-SuperBuild/blob/6962ac56ab9608d2d6174334a9a545e6a3f02d8a/docker/entrypoint.sh#L42

There should be no problem using the numbers there.
