### ISSUE TITLE
VM: Install python packages fails on uninstall pexpect

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#742]
Trying to create a new VM.

For whatever reason
https://github.com/SyneRBI/SIRF-SuperBuild/blob/ec4b9c50bb650101e232590405c06eaf417256a6/VirtualBox/scripts/INSTALL_python_packages.sh#L70
triggers an uninstall of `pexpect` with `pip`, but this fails as there's one installed by `apt` I guess.

screenshot (sorry, no copy-paste capability on this VM yet)
 ![image](https://user-images.githubusercontent.com/6362141/178552937-623f0742-a178-4a10-ab99-e14aaed95cae.png)

The installed package is at `/usr/lib/python3/dist-packages/pexpect`. Maybe it got there via https://github.com/SyneRBI/SIRF-SuperBuild/blob/d9de45ba5163eb175d6bb8cd37a2031755fd4d26/VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh#L39-L40

**Comment by KrisThielemans** [comment]
Currently trying by using docker scripts instead. This seems to work ok.

**Comment by KrisThielemans** [comment]
Suggestions:
1. replace https://github.com/SyneRBI/SIRF-SuperBuild/blob/d9de45ba5163eb175d6bb8cd37a2031755fd4d26/VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh#L39-L43 with a call to `docker/build_python-ubuntu.sh`
2. in `INSTALL_python_packages.sh` call `user_python-ubuntu.sh` as in our GHA script, as well as `INSTALL_DIR=~/devel user_service-ubuntu.sh` (which installs jupyter as well as SIRF-Exercises and CIL-Demos and does the `nbstripout` stuff)
3.  add `source ~/virtualenv/bin/activate` to `.sirfrc` or `.bashrc`

I'm not sure about the last step.

**Comment by KrisThielemans** [comment]
I note though that the docker scripts don't seem to install `cython3`. @paskino isn't this needed by Astra?

**Comment by paskino** [comment]
yes, cython3 is used by ASTRA and CCPi-Regularisation. I may have noticed a line saying cython2, some time ago in the build output

**Comment by paskino** [comment]
pexpect is required to install jupyter, but it is already installed by some other dependency:

```
apt-cache rdepends python3-pexpect
```
returns a list of which only `sosreport` is installed.

**Comment by paskino** [comment]
`python3-pexpect` is installed as part of the [base image](https://app.vagrantup.com/bento/boxes/ubuntu-18.04) 

I will uninstall it, as only `sosreport` depends on it.

**Comment by paskino** [comment]
The problem moves now to Cython.

Our FindCython.cmake isn't particularly smart and will only try to find the executable in the path.
https://github.com/SyneRBI/SIRF-SuperBuild/blob/3ba4dc86ff6c8ee7ffab76369b68a5f394809639/CMake/FindCython.cmake#L11-L30

In the VM, Cython used to be installed by the system, now it is installed by `pip`. Although `pip`'s bin directory is in the path, it is not in the path of the running shell!

**Comment by paskino** [comment]
I'm currently working on the [`VM_3.3.0`](https://github.com/SyneRBI/SIRF-SuperBuild/tree/VM_3.3.0) branch.

The build fails on installing `numba`.

```
default: Collecting git+https://github.com/data-exchange/dxchange.git (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 14))
    default:   Cloning https://github.com/data-exchange/dxchange.git to /tmp/pip-xhprbe_z-build
    default: Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/dist-packages (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 1))
    default: Requirement already up-to-date: wheel in /usr/local/lib/python3.6/dist-packages (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 2))
    default: Collecting docopt (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
    default: Collecting matplotlib (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5MB)
    default: Collecting ismrmrd-python-tools from git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 5))
    default:   Cloning https://github.com/ismrmrd/ismrmrd-python-tools.git (to master) to /tmp/pip-build-k4sxtvwq/ismrmrd-python-tools
    default: Collecting Cython (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 6))
    default:   Downloading https://files.pythonhosted.org/packages/85/f6/7ea4d1e0af39a4be28c2ee7cb79279395d2a43714a04f6128b9aafab8e41/Cython-0.29.32-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.0MB)
    default: Collecting numpy (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 7))
    default:   Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    default: Collecting scipy (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 8))
    default:   Downloading https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9MB)
    default: Collecting h5py (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 9))
    default:   Downloading https://files.pythonhosted.org/packages/70/7a/e53e500335afb6b1aade11227cdf107fca54106a1dca5c9d13242a043f3b/h5py-3.1.0-cp36-cp36m-manylinux1_x86_64.whl (4.0MB)
    default: Collecting Pillow (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 10))
    default:   Downloading https://files.pythonhosted.org/packages/7d/2a/2fc11b54e2742db06297f7fa7f420a0e3069fdcf0e4b57dfec33f0b08622/Pillow-8.4.0.tar.gz (49.4MB)
    default: Collecting wget (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 11))
    default:   Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
    default: Collecting six (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 12))
    default:   Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
    default: Collecting olefile (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 13))
    default:   Downloading https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip (112kB)
    default: Collecting numba (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 15))
    default:   Downloading https://files.pythonhosted.org/packages/e3/7d/3d61160836e49f40913741c464f119551c15ed371c1d91ea50308495b93b/numba-0.53.1.tar.gz (2.2MB)
    default: Collecting pandas (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 16))
    default:   Downloading https://files.pythonhosted.org/packages/c3/e2/00cacecafbab071c787019f00ad84ca3185952f6bb9bca9550ed83870d4d/pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5MB)
    default: Collecting tifffile (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 17))
    default:   Downloading https://files.pythonhosted.org/packages/42/6b/93a8ee61c6fbe20fa9c17928bd3b80484902b7fd454cecaffba42f5052cb/tifffile-2020.9.3-py3-none-any.whl (148kB)
    default: Collecting nibabel (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 18))
    default:   Downloading https://files.pythonhosted.org/packages/c3/f1/6e31b0287aed62233ec93535ac55554ec5e80c81b772b411e878c9d17179/nibabel-3.2.2-py3-none-any.whl (3.3MB)
    default: Collecting deprecation (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 19))
    default:   Downloading https://files.pythonhosted.org/packages/02/c3/253a89ee03fc9b9682f1541728eb66db7db22148cd94f89ab22528cd1e1b/deprecation-2.1.0-py2.py3-none-any.whl
    default: Collecting nose (from -r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 20))
    default:   Downloading https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl (154kB)
    default: Collecting python-dateutil>=2.1 (from matplotlib->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
    default: Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl (98kB)
    default: Collecting cycler>=0.10 (from matplotlib->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl
    default: Collecting kiwisolver>=1.0.1 (from matplotlib->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/a7/1b/cbd8ae738719b5f41592a12057ef5442e2ed5f5cb5451f8fc7e9f8875a1a/kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    default: Collecting cached-property; python_version < "3.8" (from h5py->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 9))
    default:   Downloading https://files.pythonhosted.org/packages/48/19/f2090f7dad41e225c7f2326e4cfe6fff49e57dedb5b53636c9551f86b069/cached_property-1.5.2-py2.py3-none-any.whl
    default: Collecting llvmlite<0.37,>=0.36.0rc1 (from numba->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 15))
    default:   Downloading https://files.pythonhosted.org/packages/19/66/6b2c49c7c68da48d17059882fdb9ad9ac9e5ac3f22b00874d7996e3c44a8/llvmlite-0.36.0.tar.gz (126kB)
    default: Collecting pytz>=2017.2 (from pandas->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 16))
    default:   Downloading https://files.pythonhosted.org/packages/60/2e/dec1cc18c51b8df33c7c4d0a321b084cf38e1733b98f9d15018880fb4970/pytz-2022.1-py2.py3-none-any.whl (503kB)
    default: Collecting packaging>=14.3 (from nibabel->-r /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/../../docker/requirements.txt (line 18))
    default:   Downloading https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40kB)
    default: Building wheels for collected packages: docopt, Pillow, wget, olefile, numba, llvmlite
    default:   Running setup.py bdist_wheel for docopt: started
    default:   Running setup.py bdist_wheel for docopt: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
    default:   Running setup.py bdist_wheel for Pillow: started
    default:   Running setup.py bdist_wheel for Pillow: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/a7/69/9a/bba9fca6782340f88dbc378893095722a663cbc618e58fe401
    default:   Running setup.py bdist_wheel for wget: started
    default:   Running setup.py bdist_wheel for wget: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
    default:   Running setup.py bdist_wheel for olefile: started
    default:   Running setup.py bdist_wheel for olefile: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/4b/f4/11/bc4166107c27f07fd7bba707ffcb439619197638a1ac986df3
    default:   Running setup.py bdist_wheel for numba: started
    default:   Running setup.py bdist_wheel for numba: finished with status 'error'
    default:   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k4sxtvwq/numba/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp081zs0gepip-wheel- --python-tag cp36:
    default:   Traceback (most recent call last):
    default:     File "<string>", line 1, in <module>
    default:     File "/tmp/pip-build-k4sxtvwq/numba/setup.py", line 422, in <module>
    default:       metadata['ext_modules'] = get_ext_modules()
    default:     File "/tmp/pip-build-k4sxtvwq/numba/setup.py", line 148, in get_ext_modules
    default:       import numpy.distutils.misc_util as np_misc
    default:   ModuleNotFoundError: No module named 'numpy'
    default:
    default:   ----------------------------------------
    default:   Running setup.py clean for numba
    default:   Failed building wheel for numba
    default:   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k4sxtvwq/numba/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
    default:   Traceback (most recent call last):
    default:     File "<string>", line 1, in <module>
    default:     File "/tmp/pip-build-k4sxtvwq/numba/setup.py", line 422, in <module>
    default:       metadata['ext_modules'] = get_ext_modules()
    default:     File "/tmp/pip-build-k4sxtvwq/numba/setup.py", line 148, in get_ext_modules
    default:       import numpy.distutils.misc_util as np_misc
    default:   ModuleNotFoundError: No module named 'numpy'
    default:
    default:   ----------------------------------------
    default:   Running setup.py bdist_wheel for llvmlite: started
    default:   Failed cleaning build dir for numba
    default:   Running setup.py bdist_wheel for llvmlite: finished with status 'error'
    default:   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k4sxtvwq/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzyy_551fpip-wheel- --python-tag cp36:
    default:   running bdist_wheel
    default:   /usr/bin/python3 /tmp/pip-build-k4sxtvwq/llvmlite/ffi/build.py
    default:   LLVM version... Traceback (most recent call last):
    default:     File "/tmp/pip-build-k4sxtvwq/llvmlite/ffi/build.py", line 220, in <module>
    default:       main()
    default:     File "/tmp/pip-build-k4sxtvwq/llvmlite/ffi/build.py", line 210, in main
    default:       main_posix('linux', '.so')
    default:     File "/tmp/pip-build-k4sxtvwq/llvmlite/ffi/build.py", line 134, in main_posix
    default:       raise RuntimeError(msg) from None
    default:   RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    default:   error: command '/usr/bin/python3' failed with exit status 1
    default:
    default:   ----------------------------------------
    default:   Running setup.py clean for llvmlite
    default:   Failed building wheel for llvmlite
    default: Successfully built docopt Pillow wget olefile
    default: Failed to build numba llvmlite
```

**Comment by paskino** [comment]
How does pip install from a `requirements.txt` file? Does it proceed row by row?

**Comment by paskino** [comment]
OK, I have now passed the install prerequisites step! 
Next problem in line:

```
CMake Error at SuperBuild/External_astra-toolbox.cmake:32 (message):
    default:   astra-toolkit binding to Python depends on Cython
```

And as [mentioned ](https://github.com/SyneRBI/SIRF-SuperBuild/issues/742#issuecomment-1205226105) I need to make the find Cython accept hints.

**Comment by KrisThielemans** [comment]
> In the VM, Cython used to be installed by the system, now it is installed by pip. Although pip's bin directory is in the path, it is not in the path of the running shell!

why not add the pip stuff to the path first? Makes sense anyway. (`~/.local/bin` or something)

**Comment by KrisThielemans** [comment]
I see you're doing `{APT_GET_INSTALL` stuff in `INSTALL_python_packages.sh`. That doesn't seem to make sense to me. (In docker, it sits in [build_python-ubuntu.sh](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/build_python-ubuntu.sh), so why not call that from `INSTALL...apt-get.sh`?

**Comment by paskino** [comment]
> I see you're doing `{APT_GET_INSTALL` stuff in `INSTALL_python_packages.sh`. That doesn't seem to make sense to me. (In docker, it sits in [build_python-ubuntu.sh](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/build_python-ubuntu.sh), so why not call that from `INSTALL...apt-get.sh`?

Yeah, I'll clean it up, once I get it to run. 

> why not add the pip stuff to the path first? Makes sense anyway. (~/.local/bin or something)

This seems to be added in a new shell, but not for the running one! So after the pip install step, before running the cmake stuff I will have to set the path.

**Comment by paskino** [comment]
>     default:   RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
>     default:   error: command '/usr/bin/python3' failed with exit status 1
>     default:
>     default:   ----------------------------------------
>     default:   Running setup.py clean for llvmlite
>     default:   Failed building wheel for llvmlite
>     default: Successfully built docopt Pillow wget olefile
>     default: Failed to build numba llvmlite
> ```

was fixed by selecting numba < 0.51, see https://github.com/numba/llvmlite/issues/621 and https://numba.discourse.group/t/numba-0-50-0-and-llvmlite-0-33-0-released/19

**Comment by paskino** [comment]
After installation of all dependencies the build gets to find Cython but it is not found.

Notice that I try on the default location `/usr/local/bin/cython` and on what I think it should be for a pip install for the user, `${HOME}/.local/bin`. I am not sure this is right, however, since the install is done by vagrant with the user vagrant (I think?)

```
--
 Looking for Cython among /usr/bin/cython3;/home/sirfuser/.local/bin/cython
    default: statusTrying with /usr/bin/cython3
    default: statusTrying with /home/sirfuser/.local/bin/cython
    default: CMake Warning at CMake/FindCython.cmake:54 (message):
    default:   Cython not found!
    default: Call Stack (most recent call first):
    default:   SuperBuild/External_astra-toolbox.cmake:30 (find_package)
    default:   CMake/ExternalProjectDependency.cmake:593 (include)
    default:   SuperBuild/External_astra-python-wrapper.cmake:29 (ExternalProject_Include_Dependencies)
    default:   CMake/ExternalProjectDependency.cmake:593 (include)
    default:   SuperBuild/External_CIL-ASTRA.cmake:28 (ExternalProject_Include_Dependencies)
    default:   CMake/ExternalProjectDependency.cmake:593 (include)
    default:   CMake/ExternalProjectDependency.cmake:639 (ExternalProject_Include_Dependencies)
    default:   SuperBuild.cmake:329 (ExternalProject_Include_Dependencies)
    default:   CMakeLists.txt:42 (include)
    default:
    default:
    default: CMake Error at SuperBuild/External_astra-toolbox.cmake:32 (message):
    default:   astra-toolkit binding to Python depends on Cython
```

I tried to use `sudo -u sirfuser python -m pip install -U -r requirements.txt` but it still failed (I'll try again)

```
default: python3: can't open file 'sirfuser': [Errno 2] No such file or directory
    default: An error occurred in /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/INSTALL_python_packages.sh at line 76. Current working-dir: /home/sirfuser/devel/SIRF-SuperBuild
```

**Comment by KrisThielemans** [comment]
2 possible reasons I think:
- you set the `PATH` for the user running in vagrant, but not `sirfuser`, which is used to launch `UPDATE.sh`
- it's overriden anyway:
https://github.com/SyneRBI/SIRF-SuperBuild/blob/3ba4dc86ff6c8ee7ffab76369b68a5f394809639/VirtualBox/scripts/UPDATE.sh#L146

There's `/usr/local/bin/cython` (automatically in the`PATH`). Is that the one to use?

**Comment by KrisThielemans** [comment]
after putting that in, I get
![image](https://user-images.githubusercontent.com/6362141/184530382-b24085c7-7aba-4e1b-a16a-04ba0a260af5.png)
of which the important bit seems
```
error: can combine user with prefix: exec_prefix/home or install_(plat)base
```
Indeed the command seems to have `--user --prefix=...`.

**Comment by KrisThielemans** [comment]
By the way, not sure if it's a great idea to `apt install python3-pip`. Might be better to install `pip` using its script (as we did in our `.travis.yml`) as this is dragging in a few other packages, which could lead to trouble.

**Comment by KrisThielemans** [comment]
The way that I debug these things is to comment out the `UPDATE.sh` call in `Vagrantfile`, do `vagrant up`, and just call `UPDATE.sh` by hand in the terminal once all done. (You can even create a snapshot before doing that, such that you never have to rebuild the VM until this is sorted out).

**Comment by KrisThielemans** [comment]
I've pushed a commit that should fix the `cython` problem to the branch

**Comment by paskino** [comment]
Download pip as in the docker files
https://github.com/SyneRBI/SIRF-SuperBuild/blob/3ba4dc86ff6c8ee7ffab76369b68a5f394809639/docker/user_python-ubuntu.sh#L41-L46
