### ISSUE TITLE
docker: fix mamba libarchive.so.13 not found

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#826]
https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/5558774566/jobs/10155960751#step:6:5431
```
#47 38.34 + mamba update -c conda-forge -y setuptools pip
#47 38.57 Traceback (most recent call last):
#47 38.57   File "/opt/conda/bin/mamba", line 7, in <module>
#47 38.57     from mamba.mamba import main
#47 38.57   File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
#47 38.57     import libmambapy as api
#47 38.57   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
#47 38.57     raise e
#47 38.57   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
#47 38.57     from libmambapy.bindings import *  # noqa: F401,F403
#47 38.57     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#47 38.57 ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```
sigh.

Possible fix
https://github.com/bird-house/finch/pull/245

**Comment by casperdcl** [comment]
Managed to reproduce this :) but the fix isn't working :/

**Comment by casperdcl** [comment]
realfix: https://mamba.readthedocs.io/en/latest/mamba-installation.html :)
