### ISSUE TITLE
CIL tests are failing due to missing pywt

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#861]
https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/7742365193/job/21226857881?pr=858#step:11:1032
```
14/18 Test #14: CIL_FRAMEWORK_TESTS_11 ...........***Failed    1.11 sec
E
======================================================================
ERROR: test_quality_measures (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_quality_measures
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/test/test_quality_measures.py", line 28, in <module>
    from cil.processors import Slicer
  File "/home/runner/install/python/cil/processors/__init__.py", line 24, in <module>
    from .RingRemover import RingRemover
  File "/home/runner/install/python/cil/processors/RingRemover.py", line 22, in <module>
    import pywt
ModuleNotFoundError: No module named 'pywt'
```

This might be fixed by installing pywt. However, as before, I'm a bit warry of depending on CIL master. Does SIRF-SuperBuild/SIRF really be at highest CIL version? I think it is probably better to fix to a hash, even with `DEVEL_BUILD=ON`.

**Comment by KrisThielemans** [comment]
using `pywavelets` as opposed to the (non-existing) `pywt` works in #862

**Comment by KrisThielemans** [comment]
This was resolved by adding pywavelets.
